### PR TITLE
[Fix #26] Fix static_files trail

### LINKED ISSUE #26: static_files as an env variable is not good for releases
Files in releases are placed under `lib/cowboy_swagger-…/…`.
The proper way to find that path would be:
```erlang
filename:join(code:priv_dir(cowboy_swagger), "swagger")
```

### PR DESCRIPTION
**Pull request by harenson**
And upgrades trails dependency

### CODE REVIEW

File: src/cowboy_swagger_handler.erl [hunk 1]
```diff
@@ -58,8 +58,13 @@ handle_get(Req, State) ->
...
 %%      that returns the `swagger.json'.
 trails() ->
-  StaticFiles = application:get_env(
-    cowboy_swagger, static_files, "priv/swagger"),
+  CowboySwaggerPriv = cowboy_swagger_priv(),
+  SwaggerPrivDir = filename:join(CowboySwaggerPriv, "swagger"),
+  StaticFiles =
+    case application:get_env(cowboy_swagger, static_files) of
+      {ok, Val} -> Val;
+      _         -> SwaggerPrivDir
```
Comment (elbrujohalcon) [inline src/cowboy_swagger_handler.erl]: The idea of evaluating `cowboy_swagger_priv()` here, instead of doing `StaticFiles = application:get_env(cowboy_swagger, static_files, cowboy_swagger_priv())` was to avoid the evaluation of said function if it wasn't actually needed. So, you should either do
```erlang
StaticFiles = application:get_env(cowboy_swagger, static_files, cowboy_swagger_priv())
```
if you don't think we need to optimize that code just yet or…
```erlang
case application:get_env(cowboy_swagger, static_files) of
  {ok, Val} -> Val;
  _         -> filename:join(cowboy_swagger_priv(), "swagger"),
end
```
…if you do ;)

Comment (harenson) [inline src/cowboy_swagger_handler.erl]: @elbrujohalcon You're right, let me change it.
